#ifndef 7WONDERSCOMMON_GLOBAL_H
#define 7WONDERSCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(7WONDERSCOMMON_LIBRARY)
#  define 7WONDERSCOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define 7WONDERSCOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // 7WONDERSCOMMON_GLOBAL_H
